corrected typos

diff --git a/.github/workflows/test-action.yml b/.github/workflows/test-action.yml
--- a/.github/workflows/test-action.yml
+++ b/.github/workflows/test-action.yml
@@ -4,17 +4,17 @@ jobs:
   test:
     runs-on: ubuntu-latest
     steps:
-      - name: Checout the repo to use it locally
+      - name: Checkout the repo to use it locally
         uses: actions/checkout@v6
       - name: Run my own container action
         id: my-action
         uses: ./
-          with:
-            who-to-great: '@wulfland'
+        with:
+          who-to-greet: '@wulfland'
       - name: Output the answer
-        run: echo "The answer is ${{steps.my-action.outputs.answer}}
+        run: echo "The answer is ${{ steps.my-action.outputs.answer }}"
       - name: Test the container
-        if: ${{steps.my-action.outputs.answer != 42}}
+        if: ${{ steps.my-action.outputs.answer != 42 }}
         run: |
-            echo "::error file=entrypoint.sh line=4 title=Error in container::The answer was not expected"
-            exit 1
+          echo "::error file=entrypoint.sh,line=4,title=Error in container::The answer was not expected"
+          exit 1
